run:
  go: "1.23"
  timeout: 10m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint

linters-settings:
  goimports:
    local-prefixes: github.com/orltom/on-call-schedule/
  revive:
    ignore-generated-header: true
    severity: warning
    enable-all-rules: false
    confidence: 0.1
    rules:
      - name: early-return
      - name: error-strings
      - name: unexported-return
      - name: unused-parameter
      - name: use-any
      - name: deep-exit
      - name: empty-lines
  gci:
    sections:
      - standard
      - default
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: goCamel

issues:
  exclude-rules:
    - path: cmd/.*
      linters:
        - forbidigo
        - funlen
    - path: _test.go
      linters:
        - funlen
        - dupl
    - path: pkg/apis/team_types.go
      linters:
        - wrapcheck
