run:
  go: 1.23
  timeout: 10m
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - depguard
    - varnamelen
    - lll
    - mnd
    - gomnd
    - testpackage
    - wsl
    - paralleltest

linters-settings:
  goimports:
    local-prefixes: github.com/orltom/on-call-schedule/
  stylecheck:
    go: "1.23"
  gosimple:
    go: "1.23"
  staticcheck:
    go: "1.23"
  revive:
    ignore-generated-header: true
    severity: warning
    enable-all-rules: false
    confidence: 0.1
    rules:
      - name: early-return
      - name: error-strings
      - name: unexported-return
      - name: unused-parameter
      - name: use-any
      - name: deep-exit
      - name: empty-lines
      - name: imports-blacklist
        arguments:
          - "log" # -> github.com/go-logr/logr
  gci:
    sections:
      - standard
      - default
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: goCamel

issues:
  exclude-rules:
    - path: cmd/.*
      linters:
        - forbidigo
    - path: _test.go
      linters:
        - funlen