name: Build and Release ocsctl

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o ocsctl -ldflags '-s -w' ./cmd

      - name: Upload Release Asset
        uses:  actions/upload-artifact@v4
        with:
          name: ocsctl-linux-amd64
          path: ocsctl
